const Invoices = [
  {
    vendor: 'Dixa',
    logoUrl: '/assets/png/vendors/dixa.png',
    verified: false,
    decsription: 'Subscription for Sales CRM',
    status: 'Scanned',
    issues: 2,
    timeInStage: '4d 21h',
    approver: 'Not set',
    approverAction: null,
    paymentDate: '5/19/12',
    toBePaid: '$779.58',
  },
  {
    vendor: 'Amazon AWS',
    logoUrl: '/assets/png/vendors/aws.png',
    verified: true,
    decsription: 'App hosting for Q3',
    status: 'Scanned',
    issues: 0,
    timeInStage: '1d 21h',
    approver: 'Not set',
    approverAction: null,
    paymentDate: '5/19/12',
    toBePaid: '$779.58',
  },
  {
    vendor: 'Missing',
    logoUrl: null,
    verified: false,
    decsription: 'Creative tool needed for graphics in marketing team',
    status: 'Scanned',
    issues: 2,
    timeInStage: '15h',
    approver: 'Not set',
    approverAction: null,
    paymentDate: '5/19/12',
    toBePaid: '$779.58',
  },
  {
    vendor: 'Oracle',
    logoUrl: null,
    verified: false,
    decsription: 'Analytics tool subscription',
    status: 'Scanned',
    issues: 2,
    timeInStage: '2d 5h',
    approver: 'Not set',
    approverAction: null,
    paymentDate: '5/19/12',
    toBePaid: '$779.58',
  },
  {
    vendor: 'Twillio',
    logoUrl: '/assets/png/vendors/twillio.png',
    verified: true,
    decsription: 'HR tool',
    status: 'Scanned',
    issues: 0,
    timeInStage: '1d 2h',
    approver: 'Not set',
    approverAction: null,
    paymentDate: '5/19/12',
    toBePaid: '$779.58',
  },
  {
    vendor: 'Hopin',
    logoUrl: null,
    verified: false,
    decsription: 'API service used for notofication services',
    status: 'Scanned',
    issues: 0,
    timeInStage: '11d 6h',
    approver: 'Not set',
    approverAction: null,
    paymentDate: '5/19/12',
    toBePaid: '$779.58',
  },
  {
    vendor: 'DocuSign',
    logoUrl: '/assets/png/vendors/docusign.png',
    verified: true,
    decsription: 'online event tool for marketing event',
    status: 'Scanned',
    issues: 0,
    timeInStage: '3d 21h',
    approver: 'Not set',
    approverAction: null,
    paymentDate: '5/19/12',
    toBePaid: '$779.58',
  },
  {
    vendor: 'Chargebee',
    logoUrl: null,
    verified: false,
    decsription: 'Recurring subs for our signatures',
    status: 'Pending',
    issues: '1/3',
    timeInStage: '5d 17h',
    approver: 'Darlene Robertson',
    approverAction: 'Remind',
    paymentDate: '5/19/12',
    toBePaid: '$779.58',
  },
  {
    vendor: 'Mailchimp',
    logoUrl: null,
    verified: false,
    decsription: 'Payment providor',
    status: 'Pending',
    issues: '1/3',
    timeInStage: '11d 15h',
    approver: 'Darlene Robertson',
    approverAction: 'Re-assign',
    paymentDate: '5/19/12',
    toBePaid: '$779.58',
  },
  {
    vendor: 'Mixpanel',
    logoUrl: '/assets/png/vendors/mixpanel.png',
    verified: true,
    decsription: 'Newsletter and landing page subscription',
    status: 'Scanned',
    issues: 0,
    timeInStage: '2d 6h',
    approver: 'Not set',
    approverAction: null,
    paymentDate: '5/19/12',
    toBePaid: '$779.58',
  },
  {
    vendor: 'HotJar',
    logoUrl: null,
    verified: false,
    decsription: 'Web analytics tool for marketing team',
    status: 'Scanned',
    issues: 0,
    timeInStage: '5d 2h',
    approver: 'Not set',
    approverAction: null,
    paymentDate: '5/19/12',
    toBePaid: '$779.58',
  },
  {
    vendor: 'Forecast',
    logoUrl: "/assets/png/vendors/forecast.png",
    verified: true,
    decsription: 'project mgmt tool for tech team',
    status: 'Scanned',
    issues: 0,
    timeInStage: '4d 16h',
    approver: 'Not set',
    approverAction: null,
    paymentDate: '5/19/12',
    toBePaid: '$779.58',
  },
  {
    vendor: 'HubSpot',
    logoUrl: null,
    verified: false,
    decsription: 'sales tool',
    status: 'Scanned',
    issues: 0,
    timeInStage: '1d 22h',
    approver: 'Not set',
    approverAction: null,
    paymentDate: '5/19/12',
    toBePaid: '$779.58',
  },
]

export default Invoices