import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="min-h-screen bg-yellow-700">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-6 pt-10">
        {/* invoices header */}
        <div className='flex items-center justify-between '>
          <h3 className='font-medium text-2xl'>Invoices</h3>
          <button className='font-normal text-sm border-gray-400 border rounded py-[6px] px-3'>New Invoice</button>
        </div>

        <div className='min-w-full flex items-end gap-5 pt-6 border-gray-100 border-b'>
          {/* invoices tabs */}
          {tabs.map((tab, index) => (
            <div key={index} className='flex items-center justify-between'>
              <div className='flex items-center relative'>
                <h4 className={`relative font-medium text-sm px-2 ${tab.selected ? 'border border-b-gray-900' : 'text-gray-500'}`}>{tab.name}
                  {tab.count > 0 &&
                    <span className='absolute ml-[2px] mb-2 text-xs text-gray-400'>{tab.count}</span>
                  }
                  {tab.status &&
                    <span className='absolute mt-1 ml-[2px] h-1 w-1 rounded-full bg-sky-600'></span>
                  }
                </h4>
              </div>

            </div>
          ))}
        </div>

      </main>
    </div>
  )
}
