import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="min-h-screen bg-yellow-700">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full">
        <div className='bg-black min-h-screen min-w-full'>
          <h1 className='text-gray-700'>asd</h1>
          <h2>asdasd</h2>
          <div className='flex space-x-1'>
            <div>asdasd</div>
            <div>asdasdasd</div>
          </div>
        </div>
      </main>

      <footer className="">

      </footer>
    </div>
  )
}
