import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="min-h-screen bg-yellow-700">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-6 pt-10">
        {/* invoices header */}
        <div className='flex items-center justify-between '>
          <h3 className='font-medium text-2xl'>Invoices</h3>
          <button className='font-normal text-sm border-gray-400 border rounded py-[6px] px-3'>New Invoice</button>
        </div>

        <div className='min-w-full flex items-end gap-5 pt-6 border-gray-100 border-b'>
          {/* invoices tabs */}
          {tabs.map((tab, index) => (
            <div key={index} className='flex items-center justify-between'>
              <div className='flex items-center relative'>
                <h4 className={`relative font-medium text-sm px-2 ${tab.selected ? 'border border-b-gray-900' : 'text-gray-500'}`}>{tab.name}
                  {tab.count > 0 &&
                    <span className='absolute ml-[2px] mb-2 text-xs text-gray-400'>{tab.count}</span>
                  }
                  {tab.status &&
                    <span className='absolute mt-1 ml-[2px] h-1 w-1 rounded-full bg-sky-600'></span>
                  }
                </h4>
              </div>

            </div>
          ))}
        </div>

        <div className='flex items-center justify-between pt-4'>
          {/* search bar */}
          <div className='flex items-center space-x-4'>
            <div className='py-[10px] px-4 rounded w-[402px] h-10 bg-gray-200'>
              <div className='flex items-center justify-between'>
                <div className='flex items-center'>
                  <div className=''>
                    <Search stroke='#A8A29E' />
                  </div>
                  <input className='bg-transparent text-sm font-normal text-white w-full h-full pl-4' placeholder='Search...' />
                </div>
              </div>
            </div>
            <button className='flex items-center gap-2'>
              <Plus />
              <h6 className='font-medium text-sm'>Add filter</h6>
            </button>
          </div>
          <Gear />
        </div>


        {/* invoices table */}
        <div className='mt-6 border-gray-200 border rounded-[4px] text-xs font-medium whitespace-nowrap'>
          <div className='flex items-center'>
            <input type='checkbox' className='w-5 h-5 border bg-gray-400 mr-4 ml-2 my-2' />
            <h6 className='w-[304px]'>Vendor</h6>
            <h6 className='w-[472px]'>Description</h6>
            <h6 className='w-[216px]'>Status</h6>
            <h6 className='w-[128px]'>Time in stage</h6>
            <h6 className='w-[348px]'>Approver</h6>
            <h6 className='w-[152px]'>Paym. date</h6>
            <h6 className='w-[96px]'>To be paid</h6>
          </div>
          {/* map invoices */}
          {Invoices.map((invoice, index) => (
            <InvoiceListItem key={index} invoice={invoice} />
          ))}
        </div>
      </main>
    </div>
  )
}
